"""add unique constraint to timesheet plans

Revision ID: 1c817d9afac3
Revises: afa26bd27bde
Create Date: 2026-09-01 11:26:13.006737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c817d9afac3'
down_revision: Union[str, Sequence[str], None] = 'afa26bd27bde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_timesheet_plan_employee_date', 'timesheet_plans', ['employee_id', 'work_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_timesheet_plan_employee_date', 'timesheet_plans', type_='unique')
    # ### end Alembic commands ###
