"""add organizations and employee organization

Revision ID: c8e84ff7c654
Revises: 6f1b18f30927
Create Date: 2026-08-31 20:30:25.219097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e84ff7c654'
down_revision: Union[str, Sequence[str], None] = '6f1b18f30927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('full_name', sa.String(length=500), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('taxation_system', sa.String(length=100), nullable=False),
    sa.Column('director', sa.String(length=200), nullable=False),
    sa.Column('chief_accountant', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn')
    )
    op.add_column('employees', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'employees', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'organization_id')
    op.drop_table('organizations')
    # ### end Alembic commands ###
