"""add fixed flag to timesheet plans

Revision ID: ca0d1f243e12
Revises: ab6111dcf629
Create Date: 2026-09-02 01:12:08.428596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca0d1f243e12'
down_revision: Union[str, Sequence[str], None] = 'ab6111dcf629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "timesheet_plans",
        sa.Column(
            "is_fixed",
            sa.Boolean(),
            nullable=True,
        ),
    )

    op.execute(
        "UPDATE timesheet_plans "
        "SET is_fixed = FALSE "
        "WHERE is_fixed IS NULL"
    )

    op.alter_column(
        "timesheet_plans",
        "is_fixed",
        existing_type=sa.Boolean(),
        nullable=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timesheet_plans', 'is_fixed')
    # ### end Alembic commands ###
